import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

export const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-sans'
})

export const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: '600',
  variable: '--font-heading'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  );
}
